apiVersion: apps/v1

kind: StatefullSet
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    app: mongo
  spec:
    containers:
      - name: mongo
        image: mongo:4.4.18
        ports:
        - containerPort: 80