apiVersion: apps/v1

kind: Deployement
metadata:
  name: studentportfolio
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: studentportfolio

## Pod Template
  template:
    metadata:
      labels:
        app: studentportfolio
    spec:
      containers:
      - name: studentportfolio
        image: studentportfolio:latest
        ports:
          - containerPort: 80
            name: http

## Health Probes
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 10

## Resource Management
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: 256Mi"
  